### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by landjea** [GeneaLabs/laravel-governor#10]
If your aim is for more advanced developers, ignore this suggestion, but it appears you are trying to make this very beginner friendly.

Policies - you give a great example of a Model Policy but you don't explain anything about it for the beginner. Like if they need it, why they need it, where to put it, when to create it.

Usage examples. Sure, they can open the vendor folder and check out how you do it, or the laravel docs for the @can information but, again, for those beginners, they aren't going to have any idea about that stuff so maybe a few usage examples would help them.

Anyway, just some thoughts. Again, disregard if this package isn't intended for beginners.

Thanks.

**Comment by mikebronner** [comment]
No, those are valid points, will add that to the documentation. :) thanks for the suggestions!

**Comment by landjea** [comment]
No problem, if I was any good at documentation I would add it for you but I would confuse the hell out of a beginner. And your current simply straight-forward but encovering docs seem very good to me.

**Comment by mikebronner** [comment]
@landjea Policies have now become drastically simplified. Documentation updated. :)
