### ISSUE TITLE
error generated after running package custom seeder file

### ISSUE THREAD

**Issue by alvi1987** [GeneaLabs/laravel-governor#11]
After running package's custom seeder following error generated. What is the remedy of this problem?
```
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::save() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in D:\xampp\xampp\htdocs\eschool\vendor\genealabs\laravel-governor\database\seeds\LaravelGovernorRolesTableSeeder.php on line 19 and defined
```

**Comment by mikebronner** [comment]
I believe this error happens if there is no user in the database when you run the seeders. Can you verify that is the case? If so, I need to update the documentation to be clearer on this.

**Comment by alvi1987** [comment]
Thanks. you are absolutely right. I forgot to add user to users table. Thanks again for the quick response.

**Comment by mikebronner** [comment]
Thanks for letting me know. :) I will update the documentation to be more explicit in the order of things, and perhaps add some better error handling and messaging to the seeder as well.

**Comment by mikebronner** [comment]
Updated README documentation in 0.2.1.
