### ISSUE TITLE
New Entity problem

### ISSUE THREAD

**Issue by alvi1987** [GeneaLabs/laravel-governor#12]
I have create a new entity as your instructions stated. and I have checked my db that super admin has permission to this entity. but I am getting this 
```
HttpException in AuthorizesRequests.php line 74:
This action is unauthorized.
```
in controller function I have written like following
```
$this->authorize('view', (new User()));
        $users = User::all();
        return view('backend.users.list')->with('users', $users);
```
and my policy class is like following

```
public function view(User $user, User $users)
    {
        return $this->validatePermissions($user, 'view', 'user', $users->created_by);
    }
```

what I am missing?

**Comment by mikebronner** [comment]
Sorry for the delay -- I will take a closer look in the morning. Off the top of my head i think the $this->authorize statement is the problem.

Using laravel-governor you don't need to establish authorization rules in the code. Instead, all you do in the code is check for them in your view or controller using `Auth::user()->can()` or in your view using `@can()`.

You then set up your rules using the admin UI in Governor. Please let me know if that fixes it, or if that's not the issue.

Thanks!

**Comment by alvi1987** [comment]
sorry , didn't fin any solution yet. I am describing the problem again.

I have created an new entity named 'user'.

userpolicy file contains following code

```
public function view(User $user, User $users)
    {
        return $this->validatePermissions($user, 'view', 'user', $users->created_by);
    }
```
and as you instructed I changed my controller code to following
```
$users = User::all();
        if (\Auth::user()->can('view', $users)) {
            return view('backend.users.list')->with('users', $users);
        } else {
            return redirect('/');
        }
```
I am logging in as superadmin so i have access to this entity. but when I am trying to go to this index function its now redirecting me to ('/') as user has not permission. So what I am doing wrong?

**Comment by mikebronner** [comment]
Try this:
```php
        $users = User::all();
        if (\Auth::user()->can('view', $users->first())) {
            return view('backend.users.list')->with('users', $users);
        } else {
            return redirect('/');
        }
```

**Comment by alvi1987** [comment]
Its not working either. should I change something in policy file?

**Comment by mikebronner** [comment]
Can you post your project (or a test project that has this issue) on github or bitbucket so I can reproduce it?

**Comment by alvi1987** [comment]
ok.. it may take some time. I will knock you. thanks

**Comment by alvi1987** [comment]
here is the my project. please take a look.
```
https://github.com/alvi1987/governortest
```

**Comment by mikebronner** [comment]
thanks, i will take a look in a bit, have some other work i need to finish up first :)

**Comment by alvi1987** [comment]
ok, np

**Comment by mikebronner** [comment]
@alvi1987 can you paste the URL/route you have problems with? I have it set up on my machine and everything appears to be working.

**Comment by mikebronner** [comment]
One sec, I think I found the issue.

**Comment by alvi1987** [comment]
you can try with 
```
../../public/users
```

**Comment by mikebronner** [comment]
OK, found the issues:

1. It appears that
  ```php
          App\Providers\AuthServiceProvider::class,
  ```
  was missing from config/app.php.
2. The policy needs to be registered in `app/Providers/AuthServiceProvider.php` as follows:
  ```php
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
        User::class => UserPolicy::class,
    ];
  ```

3. Write the authorization check like this:
  ```php
    public function index() {
        $users = User::all();

        $this->authorize('view', $users->first());

        return view('backend.users.list')->with('users', $users);
    }
  ```

Let me know how that works for you. :)

**Comment by alvi1987** [comment]
Did these changes worked for your copy of my project?
I am still getting
```
HttpException in AuthorizesRequests.php line 74:
This action is unauthorized.
```
feeling hopeless

**Comment by mikebronner** [comment]
Did you create a 'user' entity in the governor admin panel? 
```
http://yourserver.dev/genealabs/laravel-governor/entities
```

**Comment by alvi1987** [comment]
yes, I create it as I said earlier.
![untitled](https://cloud.githubusercontent.com/assets/2070352/10418701/aa6038cc-7084-11e5-969a-f4d51894e942.png)

**Comment by alvi1987** [comment]
should I give my sql dump?

**Comment by alvi1987** [comment]
I have added the sql dump to repository. and for super admin login you should use
```
email: admin@admin.com
password: adminpass
```

**Comment by mikebronner** [comment]
Cool, will take a look at the SQL now.

**Comment by mikebronner** [comment]
Just tried it with your SQL dump and it works as well.

**Comment by alvi1987** [comment]
same project same same database
whats going on here?

**Comment by mikebronner** [comment]
I submitted 3 PRs that show the changes I made to make it work on my end.

**Comment by mikebronner** [comment]
Assuming this is resolved. If not, please open a new issue with the new details. Thanks! :)
