### ISSUE TITLE
Authoriztion in view partial

### ISSUE THREAD

**Issue by alvi1987** [GeneaLabs/laravel-governor#13]
I have created a partial view for navigation.

so there is a link like following
```
<li><a href="{!! URL::to('users') !!}">Users</a></li>
```

if I want to use like 

@can @cannot for this like what should I do? passing User model instance from all controller function or is there any other way?

**Comment by mikebronner** [comment]
Hi @alvi1987 :) For this I would recommend the following approach:

```php
@can('view', (new User))
<li><a href="{!! URL::to('users') !!}">Users</a></li>
@endcan
```

**Comment by alvi1987** [comment]
So I have to add User Model to all of the controllers so that navigation can use it in all views

**Comment by mikebronner** [comment]
Only for the controllers that check for permission on the User model. Normally you only would need to do this check in the UsersController. Only rarely do I need to do permission checks on models that don't belong to the controller in question.

**Comment by alvi1987** [comment]
I am describing my scenario. I am extending custom layout which holds the nav.blade.php

this link I mentioned earlier is in this nav. did you get the scenario? suppose I am using this layout with all of my controller functions which is rendering a view. can you suggest me smarter approach or solve this situation?

**Comment by mikebronner** [comment]
Sorry, I don't think I understand the problem.
You should be able to add the `@can` directive to the view without updating the controllers. Is this not the case?

**Comment by alvi1987** [comment]
ok. got it.
using like following
```
@can('view', (new App\User))
<li><a href="{!! URL::to('users') !!}">Users</a></li>
@endcan
```
so I dont have to pass the model from controller every time. thanks for your help @mikebronner

**Comment by mikebronner** [comment]
Ah, yes, sorry I forgot the FQNS of the model. :)
