### ISSUE TITLE
Update docs on website

### ISSUE THREAD

**Issue by kohenkatz** [GeneaLabs/laravel-governor#17]
The docs at https://governor.forlaravel.com/ still describe GUI management for the `Entity` type, even though it was removed two months ago.

Maybe those docs should be updated...

**Comment by mikebronner** [comment]
Yes, sorry about that. If only there was a way to keep them in synch:)

**Comment by mikebronner** [comment]
Working on this now :)

**Comment by mikebronner** [comment]
Done, documentation now synchronizes automatically
