### ISSUE TITLE
Can't see some emails when assigning roles

### ISSUE THREAD

**Issue by casenjo** [GeneaLabs/laravel-governor#19]
This started happening recently on my production server. Everything works in terms of permissions, I just can't read which emails those actually are. Any things I should be looking for to help debug this?

![screen shot 2016-05-24 at 4 17 54 pm](https://cloud.githubusercontent.com/assets/1554289/15522955/3206ed14-21cb-11e6-83bc-7a5963369db3.png)

**Comment by mikebronner** [comment]
Thanks for reporting this, I will look into it this evening or tomorrow:)

Can you provide more details if you noticed this after a specific version?

**Comment by casenjo** [comment]
I noticed it just by chance actually, but we haven't updated governor itself. We're on version 0.1.8 and the bones-macros requirement is at 0.2.36
Odd thing is that it's only certain emails that get that kind of result. I'll try to poke around more to get you more info :)

**Comment by mikebronner** [comment]
Thanks for the update. Do you have an email protection plugin installed to prevent emails scraping on your site?

Regarding the version of governor, it's so old now, I'm not sure I can help you reproduce it.

**Comment by casenjo** [comment]
So I found the problem! (It's not an issue with Governor at all :) )
While I didn't have a specific email protection plugin installed, I had enabled CloudFlare's email protection on their end, which is what was causing the issue. I didn't make the connection initially because it wasn't a plugin I installed on my server, it was a feature I enabled as an afterthought in my CloudFlare control panel

**Comment by mikebronner** [comment]
Ah! That makes sense :) Thanks for following up.
