### ISSUE TITLE
what is the difference between viewing and inspecting?

### ISSUE THREAD

**Issue by Evertt** [GeneaLabs/laravel-governor#6]

**Comment by mikebronner** [comment]
Sorry for not being clearer on that:

View: ability to see item on index pages, lists, etc. (commonly index.blade.php)
Inspect: ability to see the detail view (commonly show.blade.php).

Will update the documentation appropriately :)

**Comment by Evertt** [comment]
Thank you for clarifying. Then I have another question. Could you describe a use-case where you want a user to **not** have the right to inspect a model, but you **do** want that user to have the right to view it?

**Comment by landjea** [comment]
@Evertt - I can give you a quick example : I used to have an online text based game that allowed users to choose powers as they levelled up. I allowed them to see the list of powers available within 10 levels, but I didn't let them inspect the power until they were within 3 levels.

**Comment by mikebronner** [comment]
@Evertt @landjea Updated the documentation to also mention the various actions: https://governor.forlaravel.com. :) Thanks for highlighting that this was lacking in the documentation. Keep em coming! :)
