### ISSUE TITLE
I don't understand how you get the created_by attribute from a not-yet created entity?

### ISSUE THREAD

**Issue by Evertt** [GeneaLabs/laravel-governor#7]
In your policies you also have a method for the create action. In which you pass an entity. But when someone is about to create an entity, it hasn't been created yet. And so the created_by attribute hasn't been set yet. So how do you do that in your own projects?

Furthermore, with the created action, the ownership will always be 'own', right? So instead of doing this:

```php
class EntityPolicy extends LaravelGovernorPolicy
{
    public function create($user, Entity $entity)
    {
        return $this->validatePermissions($user, 'create', 'entity', $entity->created_by);
    }
}
```

You could better do this, right?

```php
class EntityPolicy extends LaravelGovernorPolicy
{
    public function create($user, Entity $entity)
    {
        return $this->validatePermissions($user, 'create', 'entity', $user->id);
    }
}
```

**Comment by landjea** [comment]
Well I can't answer the first question, the second one makes more sense with $entity->created_by instead of $user->id. It gives the option to allow a user to create something on behalf of someone else. $entity->created_by == $user->id would work fine when it belongs to the user.

**Comment by Evertt** [comment]
Thank you, that makes things clearer for me. :-)

**Comment by mikebronner** [comment]
To you first question:

Normally when creating a new entity, in this case an Entity instance, you will pass in a new instance that has not yet been saved. This new instance may or may not already be populated. In the event that it is not populated, created_by will be null, but in the event it already was populated, it might have your current user. However, you don't want to hardcode your user->id in to the permission, it usually is better to rely on the method parameters. This makes for a less tightly coupled, and thus easier maintainable class.

I hope this helps explain things?

**Comment by mikebronner** [comment]
If this question isn't fully answered for you, please feel free to re-open.

**Comment by Evertt** [comment]
What does governor do when created_by is null? I guess, looking at the
code, then it assumes ownership is "other", right? I would think that in
that case it's better to assume "own".

**Comment by mikebronner** [comment]
I will add a unit test to distinguish between the two. :) Will get back to you on this. While I think the current implementation is correct, it is possible I have not encountered the specific scenario in my own projects that would be sensitive to this.

**Comment by mikebronner** [comment]
@Evertt I looked into this and have concluded that the functionality as it stands is correct. If a model is being evaluated in the policy, and created_by is null, it should be treated as not created by the user being evaluated, hence `other` is the correct assumption. If you do want it to be evaluated as `own` be sure to set the created_by to the respective user before evaluating. 

If this doesn't answer your issue, please feel free to re-open. :)
