### ISSUE TITLE
Fresh install, some issues.

### ISSUE THREAD

**Issue by landjea** [GeneaLabs/laravel-governor#8]
1) You are loading the Laravel Collective HTML/Form facades. So if you use governor package install instructions with a fresh install you will get this error messge :
```
FatalErrorException in ProviderRepository.php line 146:
Class 'Collective\Html\HtmlServiceProvider' not found
```
Your install instructions need to reference the illuminate/html provider & facades or change your composer to pull down the LaravelCollective Forms&HTML provider. I recommend pulling down Laravel Collective version since the Illuminate\HTML version is being deprecated in Laravel.

-
2) With this fresh install, and only the one user created, I get the Unauthorized Access message when I try to access any role. I checked that my user is logged in AND has the "SuperAdmin" role by doing a `dd( \Auth::user() )` and `dd( \Auth::user->roles() )` on the welcome page. Here is the output of that -
```
{
"id":1,
"name":"testguy",
"email":"testguy@testing.com",
"created_at":"2015-09-29 17:01:52",
"updated_at":"2015-09-29 17:02:09",
"created_by":null
}
[
 {
 "name":"SuperAdmin",
 "description":"This role is for the main administrator of your site. They will be able to do absolutely everything. (This role cannot be edited.)",
 "created_at":"2015-09-29 17:04:40",
 "updated_at":"2015-09-29 17:04:40",
 "created_by":null,
 "pivot":{
   "user_id":1,
   "role_key":"SuperAdmin"
   }
  }
 ]
```
so it appears that it knows that my test user has the superadmin role, however the access is denied. Anything stand out?

-
3) Shouldn't the roles use an id instead of a string as "role_key" for/in the pivot table? Integer tables are lower cost, and a standard I believe *(and less prone to typos :smile: )*.

**Comment by mikebronner** [comment]
Thanks for the heads up on #1. Will update documentation shortly.

For #2: my guess is that this has to do with the implementation in the controller or the view. Could you paste the source for both? I will be happy to take a look at it. :)

Regarding 3: this is correct for a majority of cases. However, this is one case where using the string identifiers is actually more efficient in the backend determination of access rights. (At least it was prior to upgrading to Laravel's Authorization functionality. This package has been around in one form or another since late 2014.) I will certainly re-evaluate the usage of INT vs STRING id's going forward.

**Comment by landjea** [comment]
For #2 - not using any custom controller or view. I am attempting to navigate to your "roles" route @ /genealabs/laravel-governor/roles. From the install instructions, it appears that these were navigable out of the box once collision-checking was done.

**Comment by mikebronner** [comment]
Ah, gotcha ... taking a look now.

**Comment by mikebronner** [comment]
Could you take a look at your permissions table and make sure it is populated? I'm wondering if a permission isn't missing. You should see an entry for SuperAdmin with entity `role`, all 5 actions, and ownership set to `any` on all of them.

**Comment by landjea** [comment]
Sure seems like they are all there. Image attached of Permissions table
contents.

[image: Inline image 1]

**Comment by mikebronner** [comment]
Could you post your project to a temporary repo I could have a look at? I'd like to see if I can replicate the issue on my machine.

**Comment by landjea** [comment]
I can't get it to github (work proxy just refuses to let me there) but I can get it on bitbucket. You use them? Or I can put it up at github @ home tonight. Which would you prefer?

**Comment by mikebronner** [comment]
Bitbucket is great :)

**Comment by landjea** [comment]
Okee dokie. :)

**Comment by landjea** [comment]
Here you go.

https://bitbucket.org/landjea/smarch/overview

Remember, I have some dd() in place on the welcome page and am using a
quick simple layout for auth login/registration.

**Comment by landjea** [comment]
And the .env data is there because ...garbage info. It was a brand new
clean install so I didn't put any security on it yet. :)

**Comment by mikebronner** [comment]
awesome, thanks :) give me a bit to test this, will get back with you later today

**Comment by mikebronner** [comment]
@landjea I took a look at your project. The one thing that stuck out to me is that you are pulling version 0.1.0 of governor, and not ^0.1.0.
Update your composer.json to include governor like this:

```json
        "genealabs/laravel-governor": "~0.1.0",
```

**Comment by mikebronner** [comment]
Side-note: adding "laravelcollective/html" package to dependencies, should be available this afternoon.

**Comment by landjea** [comment]
I will add that to composer as soon as I get a chance, but it's weird as I copy/pasted it from the install instructions into the command line. Weird. I will let you know what happens. Thanks.

**Comment by mikebronner** [comment]
I wonder if the pasting escaped the string, and omitted the special character? Indeed, odd. Please re-open if this issue is not resolved (closing for now). :)

**Comment by landjea** [comment]
> I wonder if the pasting escaped the string, and omitted the special character?

I just did another copy/paste and cancelled the batch job right after the composer.json was updated and that is precisely what happened.

>Update your composer.json to include governor like this:
>        `"genealabs/laravel-governor": "~0.1.0",`

:+1: That seemed to work to view the pages. Haven't tried adding/editing or anything yet.
 > - Removing genealabs/laravel-governor (0.1.0)
 > - Installing genealabs/laravel-governor (0.1.8)
